"""Shared helpers for the per-step scripts in tmp/.

Loads a TOML config, resolves all paths used by the pipeline, and exposes a
single Paths dataclass that every step_*.py file consumes.

Keep this small. If a helper only matters to one stage, put it in that
step file, not here.
"""

from __future__ import annotations

import sys
import tomllib

from dataclasses import dataclass
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

REPO_ROOT = Path(__file__).resolve().parents[1]
TMP_ROOT = REPO_ROOT / "tmp"
WORK_ROOT = TMP_ROOT / "work"
DEFAULT_CONFIG = "configs/current_movie.toml"

PLACEHOLDER_ANCHORED = "<REPLACE_WITH_STAGE2_PLANNER_OUTPUT>\n"


@dataclass
class Paths:
    # Inputs from the movie folder
    movie_dir: Path
    video: Path
    subtitle_srt: Path
    style: Path

    # Per-stage work dirs (under tmp/work/<movie_slug>/)
    stage0_dir: Path
    stage1_dir: Path
    stage2_dir: Path
    stage3_dir: Path
    stage4_dir: Path
    stage5_dir: Path
    stage6_dir: Path
    stage7_dir: Path

    # Stage 0
    visual_segments: Path

    # Stage 1
    subtitles_text: Path

    # Stage 2 — prompt file generated by us, anchored_script filled by the user
    # after pasting the planner LLM's reply.
    planner_prompt: Path
    anchored_script: Path
    synopsis: Path  # optional; user-authored plot/cast/context

    # Stage 3 — filenames are derived from --tag by stage3 itself
    stage3_voiceover: Path
    stage3_manifest: Path

    # Stage 4
    stage4_subtitle_manifest: Path

    # Stage 5
    stage5_clips_dir: Path
    stage5_keyframes_dir: Path
    stage5_clip_manifest: Path

    # Stage 6
    stage6_review_video: Path

    # Stage 7
    final_video: Path
    final_video_manifest: Path


def load_config(config_path: str | Path) -> dict:
    """Read a TOML config file and return its contents as a dict."""
    config_path = Path(config_path)
    if not config_path.is_absolute():
        config_path = TMP_ROOT / config_path
    with config_path.open("rb") as f:
        return tomllib.load(f)


def build_paths(config: dict) -> Paths:
    """Resolve every path the pipeline cares about from a loaded config dict."""
    common = config["common"]
    stage3_cfg = config.get("stage3", {})

    movie_slug = common["movie_slug"]
    movie_dir = (REPO_ROOT / common["movie_dir"]).resolve()
    style = (REPO_ROOT / common["style_path"]).resolve()
    video = movie_dir / common["video_file"]
    subtitle_srt = movie_dir / common["subtitle_file"]

    work_dir = WORK_ROOT / movie_slug
    stage0_dir = work_dir / "stage0"
    stage1_dir = work_dir / "stage1"
    stage2_dir = work_dir / "stage2"
    stage3_dir = work_dir / "stage3"
    stage4_dir = work_dir / "stage4"
    stage5_dir = work_dir / "stage5"
    stage6_dir = work_dir / "stage6"
    stage7_dir = work_dir / "stage7"

    tag = stage3_cfg.get("tag") or style.stem

    return Paths(
        movie_dir=movie_dir,
        video=video,
        subtitle_srt=subtitle_srt,
        style=style,
        stage0_dir=stage0_dir,
        stage1_dir=stage1_dir,
        stage2_dir=stage2_dir,
        stage3_dir=stage3_dir,
        stage4_dir=stage4_dir,
        stage5_dir=stage5_dir,
        stage6_dir=stage6_dir,
        stage7_dir=stage7_dir,
        visual_segments=stage0_dir / "visual_segments.json",
        subtitles_text=stage1_dir / "subtitles.txt",
        planner_prompt=stage2_dir / "planner_prompt.txt",
        anchored_script=stage2_dir / "anchored_script.txt",
        synopsis=movie_dir / "synopsis.md",
        stage3_voiceover=stage3_dir / f"voiceover_{tag}_voiceclone.mp3",
        stage3_manifest=stage3_dir / f"voiceover_{tag}_voiceclone.manifest.json",
        stage4_subtitle_manifest=stage4_dir / "subtitle_manifest.json",
        stage5_clips_dir=stage5_dir / "clips",
        stage5_keyframes_dir=stage5_dir / "keyframes",
        stage5_clip_manifest=stage5_dir / "clip_manifest.json",
        stage6_review_video=stage6_dir / "review.mp4",
        final_video=stage7_dir / "final_video.mp4",
        final_video_manifest=stage7_dir / "delivery_manifest.json",
    )


def ensure_stage_dirs(paths: Paths) -> None:
    for d in (
        paths.stage0_dir,
        paths.stage1_dir,
        paths.stage2_dir,
        paths.stage3_dir,
        paths.stage4_dir,
        paths.stage5_dir,
        paths.stage6_dir,
        paths.stage7_dir,
    ):
        d.mkdir(parents=True, exist_ok=True)


def is_filled(path: Path, placeholder: str) -> bool:
    """True if the file exists and contains something other than the placeholder."""
    if not path.exists():
        return False
    return path.read_text(encoding="utf-8").strip() not in {"", placeholder.strip()}


def banner(msg: str) -> None:
    print(f"\n{'=' * 8} {msg} {'=' * 8}", flush=True)


def fail(msg: str) -> int:
    print(f"\nERROR: {msg}", file=sys.stderr)
    return 1
