"""Shared helpers for the per-step scripts in tmp/.

Loads a TOML config, resolves all paths used by the pipeline, and exposes a
single Paths dataclass that every step_*.py file consumes.

Keep this small. If a helper only matters to one stage, put it in that
step file, not here.
"""

from __future__ import annotations

import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TMP_ROOT = REPO_ROOT / "tmp"
WORK_ROOT = TMP_ROOT / "work"

PLACEHOLDER_BEATS = "<REPLACE_WITH_STAGE2_WRITER_OUTPUT>\n"
PLACEHOLDER_GROUNDED = "<REPLACE_WITH_STAGE2_GROUNDER_OUTPUT>\n"


@dataclass
class Paths:
    # Inputs from the movie folder
    movie_dir: Path
    video: Path
    subtitle_srt: Path
    style: Path

    # Per-stage work dirs (under tmp/work/<movie_slug>/)
    stage0_dir: Path
    stage1_dir: Path
    stage2_dir: Path
    stage3_dir: Path
    stage4_dir: Path
    stage5_dir: Path

    # Stage 0
    visual_segments: Path

    # Stage 1
    subtitles_text: Path

    # Stage 2 — prompt files generated by us, *_text files are filled by the user
    writer_prompt: Path
    writer_beats: Path
    grounder_prompt: Path
    grounded_script: Path

    # Stage 3 — filenames are derived from --tag by stage3 itself
    stage3_voiceover: Path
    stage3_manifest: Path

    # Stage 4
    stage4_clips_dir: Path
    stage4_keyframes_dir: Path
    stage4_clip_manifest: Path

    # Stage 5
    final_video: Path


def load_config(config_path: str | Path) -> dict:
    """Read a TOML config file and return its contents as a dict."""
    config_path = Path(config_path)
    if not config_path.is_absolute():
        config_path = TMP_ROOT / config_path
    with config_path.open("rb") as f:
        return tomllib.load(f)


def build_paths(config: dict) -> Paths:
    """Resolve every path the pipeline cares about from a loaded config dict."""
    common = config["common"]
    stage3_cfg = config.get("stage3", {})

    movie_slug = common["movie_slug"]
    movie_dir = (REPO_ROOT / common["movie_dir"]).resolve()
    style = (REPO_ROOT / common["style_path"]).resolve()
    video = movie_dir / common["video_file"]
    subtitle_srt = movie_dir / common["subtitle_file"]

    work_dir = WORK_ROOT / movie_slug
    stage0_dir = work_dir / "stage0"
    stage1_dir = work_dir / "stage1"
    stage2_dir = work_dir / "stage2"
    stage3_dir = work_dir / "stage3"
    stage4_dir = work_dir / "stage4"
    stage5_dir = work_dir / "stage5"

    tag = stage3_cfg.get("tag") or style.stem

    return Paths(
        movie_dir=movie_dir,
        video=video,
        subtitle_srt=subtitle_srt,
        style=style,
        stage0_dir=stage0_dir,
        stage1_dir=stage1_dir,
        stage2_dir=stage2_dir,
        stage3_dir=stage3_dir,
        stage4_dir=stage4_dir,
        stage5_dir=stage5_dir,
        visual_segments=stage0_dir / "visual_segments.json",
        subtitles_text=stage1_dir / "subtitles.txt",
        writer_prompt=stage2_dir / "writer_prompt.txt",
        writer_beats=stage2_dir / "writer_beats.txt",
        grounder_prompt=stage2_dir / "grounder_prompt.txt",
        grounded_script=stage2_dir / "grounded_script.txt",
        stage3_voiceover=stage3_dir / f"voiceover_{tag}_voiceclone.mp3",
        stage3_manifest=stage3_dir / f"voiceover_{tag}_voiceclone.manifest.json",
        stage4_clips_dir=stage4_dir / "clips",
        stage4_keyframes_dir=stage4_dir / "keyframes",
        stage4_clip_manifest=stage4_dir / "clip_manifest.json",
        final_video=stage5_dir / "review.mp4",
    )


def ensure_stage_dirs(paths: Paths) -> None:
    for d in (
        paths.stage0_dir,
        paths.stage1_dir,
        paths.stage2_dir,
        paths.stage3_dir,
        paths.stage4_dir,
        paths.stage5_dir,
    ):
        d.mkdir(parents=True, exist_ok=True)


def is_filled(path: Path, placeholder: str) -> bool:
    """True if the file exists and contains something other than the placeholder."""
    if not path.exists():
        return False
    return path.read_text(encoding="utf-8").strip() not in {"", placeholder.strip()}


def banner(msg: str) -> None:
    print(f"\n{'=' * 8} {msg} {'=' * 8}", flush=True)


def fail(msg: str) -> int:
    print(f"\nERROR: {msg}", file=sys.stderr)
    return 1
